
# DataSource Config
spring:
  datasource:
    # 配置数据源信息
    # type: com.zaxxer.hikari.HikariDataSource
    # 配置连接数据库的各个信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mytest?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

# 可以
#logging:
#  level:
#    com.cyl.myapp.mapper: debug

# 可以
mybatis-plus:
  configuration:
    #默认不显示SQL日志
    #    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mybatis plus 的全局配置
  global-config:
    db-config:
      # 设置实体类表的统一前缀
      table-prefix: t_

